name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Publish Application
    - name: Publish Application
      shell: pwsh
      run: dotnet publish -c Release -r win-x64 --self-contained -o ./publish

    # Download Blender
    - name: Download Blender File
      shell: pwsh
      run: curl.exe -fSLo .\blender-4.2.4-windows-x64.zip https://mirrors.iu13.net/blender/release/Blender4.2/blender-4.2.4-windows-x64.zip

    # Extract Blender File
    - name: Extract Blender File
      shell: pwsh
      run: Expand-Archive -Path ".\blender-4.2.4-windows-x64.zip"

    # Create the necessary directories and move Blender Files
    - name: Move Blender Files
      shell: pwsh
      run: |
        $sourcePath = "./blender-4.2.4-windows-x64/blender-4.2.4-windows-x64/*"
        $destinationPath = "./publish/Blender/Windows"

        # Check if the source directory exists
        if (-Not (Test-Path -Path $sourcePath)) {
            Write-Host "Source path not found: $sourcePath"
            exit 1
        }

        # Create the destination directories if they don't exist
        if (-Not (Test-Path -Path $destinationPath)) {
            New-Item -ItemType Directory -Path $destinationPath -Force | Out-Null
        }

        # Move the files
        Move-Item -Path $sourcePath -Destination $destinationPath -Force

    # Install Chocolatey
    - name: Install Chocolatey
      shell: pwsh
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    # Install Inno Setup
    - name: Install Inno Setup
      shell: pwsh
      run: choco install innosetup -y --force

    # Run Inno Setup Script
    - name: Replace version number in Inno Setup script
      shell: pwsh
      run: |
        $version = Get-Content .\VERSION
        (Get-Content .\Install\Windows\Orthographic Renderer Inno Setup.iss) -replace 'X\.Y\.Z', $version | Set-Content .\Install\Windows\Orthographic Renderer Inno Setup.iss

    # Run Inno Setup Script
    - name: Compile Installer Script
      shell: pwsh
      run: iscc ".\Install\Windows\Orthographic Renderer Inno Setup.iss"

    # Output
    - name: Upload Output
      uses: actions/upload-artifact@v4
      with:
        name: orthographic-renderer-windows-build
        path: .\Install\Windows\Output\*.exe
